---

# sites-enabled (deprecated)
- name: "conf: Link nginx/conf.d to nginx/sites-enabled (deprecated)"
  file:
    state: link
    src: "{{ nginx_conf_dir }}/nginx/conf.d"
    dest: "{{ nginx_conf_dir }}/nginx/sites-enabled"
  when: nginx_link_sites_enbled

# nginx/nginx.conf
- name: "conf: Configure {{ nginx_conf_path }}"
  template:
    src: "nginx.conf.j2"
    dest: "{{ nginx_conf_path }}"
    owner: "{{ nginx_conf_owner }}"
    group: "{{ nginx_conf_group }}"
    mode: "{{ nginx_conf_mode }}"
    backup: "{{ nginx_backup_conf }}"
    validate: nginx -t -c %s
  notify: reload nginx

# nginx/conf.d
- name: "conf: Find config files in {{ nginx_server_conf_dir }}"
  find:
    paths: "{{ nginx_server_conf_dir }}"
    patterns: "*.conf"
  delegate_to: localhost
  register: result

- name: "conf: List server files in {{ nginx_server_conf_dir }}"
  debug:
    msg: "{{ result | json_query('files[].path') }}"
  when: nginx_debug

- name: "conf: Configure servers in {{ nginx_conf_dir }}/nginx/conf.d"
  include_tasks: conf-server.yml
  loop: "{{ result | json_query('files[].path') }}"

# EOF
...
