---
# tasks for vbotka.nginx

- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  tags: [nginx-assert, always]

- name: Import vars.yml
  ansible.builtin.import_tasks: vars.yml
  tags: [nginx-vars, always]

- name: Import debug.yml
  ansible.builtin.import_tasks: debug.yml
  when: nginx_debug|bool
  tags: [nginx-debug, always]

- name: Import packages.yml
  ansible.builtin.import_tasks: packages.yml
  when: nginx_install|bool
  tags: nginx-packages

- name: Import conf.yml
  ansible.builtin.import_tasks: conf.yml
  tags: nginx-conf

- name: Import service.yml
  ansible.builtin.import_tasks: service.yml
  tags: nginx-service

# EOF
...
