---

- name: "packages: Install BSD packages"
  ansible.builtin.include_tasks: fn/packages-bsd.yml
  when: ansible_distribution in nginx_supported_bsd_distributions

- name: "packages: Install Linux packages"
  ansible.builtin.include_tasks: fn/packages-linux.yml
  when: ansible_distribution in nginx_supported_linux_distributions or
        nginx_try_linux_defaults|bool

# EOF
...
