---

- name: "service: Service BSD"
  include_tasks: service-bsd.yml
  when: ansible_distribution in nginx_supported_bsd_distribution

- name: "service: Service Linux"
  include_tasks: service-linux.yml
  when: ansible_distribution in nginx_supported_linux_distribution

# EOF
...
