---

- name: "conf:files: Configure directories and files"
  ansible.builtin.file:
    state: "{{ item.state }}"
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ nginx_files }}"
  loop_control:
    label: "{{ item.state }} {{ item.path }} {{ item.mode }} {{ item.owner }} {{ item.group }}"

# EOF
...
