---

# sites-enabled (deprecated)
- name: "conf:sites-enabled: Stat sites-enabled (deprecated)"
  ansible.builtin.stat:
    path: "{{ nginx_conf_dir }}/nginx/sites-enabled"
  register: result

- name: "conf:sites-enabled: Move sites-enabled (deprecated) to
                             sites-enabled.orig"
  command:
    cmd: >
      mv {{ nginx_conf_dir }}/nginx/sites-enabled
         {{ nginx_conf_dir }}/nginx/sites-enabled.orig
  when:
    - result.stat.exists
    - result.stat.isdir|default(false)

- name: "conf:sites-enabled: Link conf.d to sites-enabled"
  ansible.builtin.file:
    state: link
    src: conf.d
    dest: "{{ nginx_conf_dir }}/nginx/sites-enabled"
  when: not ansible_check_mode

# EOF
...
