---

- name: "conf:files: Configure directories and files"
  file:
    state: "{{ item.state }}"
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ nginx_files }}"

# EOF
...
