---

- name: "packages:linux: Update cache RH"      # Note 1
  command:                                     # noqa 303
    cmd: yum makecache
  when:
    - nginx_install_update_cache|bool
    - ansible_os_family == "RedHat"

- name: "packages:linux: Update cache Debian"  # Note 2
  ansible.builtin.apt:
    update_cache: "{{ nginx_install_update_cache }}"
    cache_valid_time: "{{ nginx_install_cache_valid_time }}"
  when:
    - nginx_install_update_cache|bool
    - ansible_os_family == "Debian"

- name: "packages:linux: Install Linux packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ nginx_packages }}"
  register: result
  retries: "{{ nginx_install_retries }}"
  until: result is succeeded
  delay: "{{ nginx_install_delay }}"

#    Notes
#
# 1) Module yum is not capable of updating cache only. See:
#    yum module requires package name for cache update #33461
#    https://github.com/ansible/ansible/issues/33461
#    (closed as notabug)
#
# 2) Module apt with update_cache:true is not idempotent

# EOF
...
