---

- name: "service:linux: Enable and Start Nginx"
  service:
    name: "{{ nginx_service }}"
    state: started
    enabled: true
  when: nginx_enable|bool

- name: "service:linux: Disable and Stop Nginx"
  service:
    name: "{{ nginx_service }}"
    state: stopped
    enabled: false
  when: not nginx_enable|bool

# EOF
...
